force_poll:
  name: "Force poll API"
  description: "[%key:component.pollen_lu.services.force_poll.description%]"
  fields:
    none:
      description: "[%key:component.pollen_lu.services.force_poll.fields.none.description%]"
